from enum import IntEnum

"""Spielfeld"""
COURT_WIDTH = 1200
COURT_HEIGHT = 680
FIELD_COLOUR = (12, 128, 40)
COURT_LINE_THICKNESS = 8
COURT_LINE_POINT_RADIUS = 10
COURT_LINE_CIRCLE_RADIUS = 103

"""Tor"""
GOAL_BAR_POS = 240
GOAL_SIZE = 200
GOAL_WIDTH = 15

"""Spielstangen"""
BAR_WIDTH = 14

BAR_POSITION_KEEPER = 75
BAR_POSITION_DEFENDER = 225
BAR_POSITION_MIDFIELDER = 525
BAR_POSITION_FORWARD = 825


class Gamer(IntEnum):
    HUMAN = 0
    COMPUTER = 1
