from enum import IntEnum
from kicker.CONST_KICKER import COURT_WIDTH
from kicker.CONST_KICKER import COURT_HEIGHT
from kicker.CONST_KICKER import BAR_POSITION_KEEPER
from kicker.CONST_KICKER import BAR_POSITION_DEFENDER
from kicker.CONST_KICKER import BAR_POSITION_MIDFIELDER
from kicker.CONST_KICKER import BAR_POSITION_FORWARD
from kicker.CONST_BALL import BALL_RADIUS

"""Spielfiguren"""
FIGURE_BODY_WIDTH = 24
FIGURE_FOOT_WIDTH = 25
FIGURE_HEAD_WIDTH = 20
FIGURE_FOOT_HEIGHT = 24
FIGURE_BODY_HEIGHT = 34
FIGURE_HEAD_HEIGHT = 20

MAX_POS_KEEPER = 242
MAX_POS_DEFENDER = 366
MAX_POS_MIDFIELDER = 114
MAX_POS_FORWARD = 230

DEFENDER_DISTANCE_BETWEEN_FIGURES = 232
MIDFIELDER_DISTANCE_BETWEEN_FIGURES = 123
FORWARD_DISTANCE_BETWEEN_FIGURES = 184

"""Y_Position of the Computer figures"""
POSITION_ON_BAR_KEEPER_COMPUTER = 219
POSITION_ON_BAR_DEFENDER_RIGHT_COMPUTER = (COURT_HEIGHT - MAX_POS_DEFENDER + DEFENDER_DISTANCE_BETWEEN_FIGURES) / 2
POSITION_ON_BAR_DEFENDER_LEFT_COMPUTER = (COURT_HEIGHT - MAX_POS_DEFENDER - DEFENDER_DISTANCE_BETWEEN_FIGURES) / 2
POSITION_ON_BAR_MIDFIELDER_RIGHT_OUTSIDE_COMPUTER = (COURT_HEIGHT - MAX_POS_MIDFIELDER - 4 * MIDFIELDER_DISTANCE_BETWEEN_FIGURES) / 2
POSITION_ON_BAR_MIDFIELDER_RIGHT_COMPUTER = (COURT_HEIGHT - MAX_POS_MIDFIELDER - 2 * MIDFIELDER_DISTANCE_BETWEEN_FIGURES) / 2
POSITION_ON_BAR_MIDFIELDER_MIDDLE_COMPUTER = (COURT_HEIGHT - MAX_POS_MIDFIELDER) / 2
POSITION_ON_BAR_MIDFIELDER_LEFT_COMPUTER = (COURT_HEIGHT - MAX_POS_MIDFIELDER + 2 * MIDFIELDER_DISTANCE_BETWEEN_FIGURES) / 2
POSITION_ON_BAR_MIDFIELDER_LEFT_OUTSIDE_COMPUTER = (COURT_HEIGHT - MAX_POS_MIDFIELDER + 4 * MIDFIELDER_DISTANCE_BETWEEN_FIGURES) / 2
POSITION_ON_BAR_FORWARD_RIGHT_COMPUTER = (COURT_HEIGHT - MAX_POS_FORWARD - 2 * FORWARD_DISTANCE_BETWEEN_FIGURES) / 2
POSITION_ON_BAR_FORWARD_MIDDLE_COMPUTER = (COURT_HEIGHT - MAX_POS_FORWARD) / 2
POSITION_ON_BAR_FORWARD_LEFT_COMPUTER = (COURT_HEIGHT - MAX_POS_FORWARD + 2 * FORWARD_DISTANCE_BETWEEN_FIGURES) / 2

"""Y_Position of the Human figures"""
POSITION_ON_BAR_KEEPER_HUMAN = 219
POSITION_ON_BAR_DEFENDER_RIGHT_HUMAN = (COURT_HEIGHT - MAX_POS_DEFENDER + DEFENDER_DISTANCE_BETWEEN_FIGURES) / 2
POSITION_ON_BAR_DEFENDER_LEFT_HUMAN = (COURT_HEIGHT - MAX_POS_DEFENDER - DEFENDER_DISTANCE_BETWEEN_FIGURES) / 2
POSITION_ON_BAR_MIDFIELDER_RIGHT_OUTSIDE_HUMAN = (COURT_HEIGHT - MAX_POS_MIDFIELDER - 4 * MIDFIELDER_DISTANCE_BETWEEN_FIGURES) / 2
POSITION_ON_BAR_MIDFIELDER_RIGHT_HUMAN = (COURT_HEIGHT - MAX_POS_MIDFIELDER - 2 * MIDFIELDER_DISTANCE_BETWEEN_FIGURES) / 2
POSITION_ON_BAR_MIDFIELDER_MIDDLE_HUMAN = (COURT_HEIGHT - MAX_POS_MIDFIELDER) / 2
POSITION_ON_BAR_MIDFIELDER_LEFT_HUMAN = (COURT_HEIGHT - MAX_POS_MIDFIELDER + 2 * MIDFIELDER_DISTANCE_BETWEEN_FIGURES) / 2
POSITION_ON_BAR_MIDFIELDER_LEFT_OUTSIDE_HUMAN = (COURT_HEIGHT - MAX_POS_MIDFIELDER + 4 * MIDFIELDER_DISTANCE_BETWEEN_FIGURES) / 2
POSITION_ON_BAR_FORWARD_RIGHT_HUMAN = (COURT_HEIGHT - MAX_POS_FORWARD - 2 * FORWARD_DISTANCE_BETWEEN_FIGURES) / 2
POSITION_ON_BAR_FORWARD_MIDDLE_HUMAN = (COURT_HEIGHT - MAX_POS_FORWARD) / 2
POSITION_ON_BAR_FORWARD_LEFT_HUMAN = (COURT_HEIGHT - MAX_POS_FORWARD + 2 * FORWARD_DISTANCE_BETWEEN_FIGURES) / 2

""" X_Position of the Game Bars """
BAR_POSITION_KEEPER_COMPUTER = 75
BAR_POSITION_KEEPER_HUMAN = 1125
BAR_POSITION_DEFENDER_COMPUTER = 225
BAR_POSITION_DEFENDER_HUMAN = 975
BAR_POSITION_MIDFIELDER_COMPUTER = 525
BAR_POSITION_MIDFIELDER_HUMAN = 675
BAR_POSITION_FORWARD_COMPUTER = 825
BAR_POSITION_FORWARD_HUMAN = 375



"""Reflektionsebenen der Spielfiguren"""
REFLECTION_PLAN_KEEPER = COURT_WIDTH - BAR_POSITION_KEEPER - FIGURE_FOOT_WIDTH - BALL_RADIUS
REFLECTION_PLAN_DEFENDER = COURT_WIDTH - BAR_POSITION_DEFENDER - FIGURE_FOOT_WIDTH - BALL_RADIUS
REFLECTION_PLAN_MIDFIELDER = COURT_WIDTH - BAR_POSITION_MIDFIELDER - FIGURE_FOOT_WIDTH - BALL_RADIUS
REFLECTION_PLAN_FORWARD = COURT_WIDTH - BAR_POSITION_FORWARD - FIGURE_FOOT_WIDTH - BALL_RADIUS

X_OFFSET_REFLECTION_PLANE = FIGURE_FOOT_WIDTH + BALL_RADIUS
Y_OFFSET_REFLECTION_PLANE = (FIGURE_FOOT_HEIGHT / 2) + BALL_RADIUS


class TeamComputer(IntEnum):
    KEEPER = 1
    DEFENDER_RIGHT = 2
    DEFENDER_LEFT = 3
    MIDFIELDER_HALF_RIGHT = 4
    MIDFIELDER_CENTER = 5
    MIDFIELDER_HALF_LEFT = 6
    MIDFIELDER_RIGHT = 7
    FORWARD_RIGHT = 8
    FORWARD_CENTER = 9
    FORWARD_LEFT = 10
    MIDFIELDER_LEFT = 11


class TeamHuman(IntEnum):
    KEEPER = 1
    DEFENDER_RIGHT = 2
    DEFENDER_LEFT = 3
    MIDFIELDER_HALF_RIGHT = 4
    MIDFIELDER_CENTER = 5
    MIDFIELDER_HALF_LEFT = 6
    MIDFIELDER_RIGHT = 7
    FORWARD_RIGHT = 8
    FORWARD_CENTER = 9
    FORWARD_LEFT = 10
    MIDFIELDER_LEFT = 11
